### ISSUE TITLE
Waffle navigator conflict problem

### ISSUE THREAD

**Issue by yujinkim1** [GDSC-Waffle-Team/waffle-flutter-app#14]
### Summary
- 계정 권한에 따라서 로드되는 스크린을 분기하는 구간에서 `classifier()` 메소드가 실행 되지 않는 문제
- `classifier()` 메소드가 실행이 되지 않아 스크린 분기를 할 수 없음

### Solution
- 완벽한 해결방법을 찾을 수 없지만, 문제를 해결하기 위한 구조를 설계하여 적용하고자 함
- 우선적으로 Flutter는 라우팅 시스템을 Stack 형식으로 사용하기 때문에 순차 접근이 될 수 밖에 없음

**Comment by yujinkim1** [comment]
https://user-images.githubusercontent.com/26790710/211472551-8f22de10-acd6-42f1-b837-65794279c3a6.mov

**Comment by yujinkim1** [comment]
### Summary
- 최초 로그인 시도 후 로그아웃을 하지 않고 재실행하면 관리자 스크린으로 정상적으로 연결됨

### Solution
- 관리자 계정으로 최초 로그인시 강제로 멤버 스크린으로 이동하는 문제를 해결하면 될 것으로 보임

**Comment by yujinkim1** [comment]
### Completed
- 관리자 계정으로 최초 로그인시 강제로 멤버 스크린으로 이동하는 문제를 해결하면 될 것으로 보임
- 계정 권한에 따른 스크린 접근 권한에 대한 이중 검사를 통해 토큰의 인증 사이클 수정

**Comment by yujinkim1** [comment]
https://user-images.githubusercontent.com/26790710/211736384-01068f85-84ab-4f41-b7ab-bba51868c668.mov

**Comment by YehyeokBang** [comment]
@yujinkim1 "ADMIN" 권한을 가진 계정으로 로그인 시 하단 NAV에 '관리' 기능을 누르면 모든 멤버의 nickname이 보여지나요?

**Comment by yujinkim1** [comment]
@YehyeokBang 해당 기능에 대해서 보여드릴 수 있어요~
